spring:
  datasource:
    username: hefeng
    password: hefeng
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    gcp:
      sql:
        database-name: blog_product
        instance-connection-name: blog-website-283307:europe-west4:chen-blog
        enabled: true
        credentials:
          location: file:/blog-key.json
      logging:
        enabled: true
server:
  port: 8080
  address: 0.0.0.0







